/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FitTextDemo {
    }
}
declare global {
    interface HTMLFitTextDemoElement extends Components.FitTextDemo, HTMLStencilElement {
    }
    var HTMLFitTextDemoElement: {
        prototype: HTMLFitTextDemoElement;
        new (): HTMLFitTextDemoElement;
    };
    interface HTMLElementTagNameMap {
        "fit-text-demo": HTMLFitTextDemoElement;
    }
}
declare namespace LocalJSX {
    interface FitTextDemo {
    }
    interface IntrinsicElements {
        "fit-text-demo": FitTextDemo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fit-text-demo": LocalJSX.FitTextDemo & JSXBase.HTMLAttributes<HTMLFitTextDemoElement>;
        }
    }
}
